### ISSUE TITLE
null-safety version

### ISSUE THREAD

**Issue by alexgrusu** [rSquared-software/flutter-hexagon#12]
Can we have the null-safety version published on pub.dev?

**Comment by orlikraf** [comment]
Sure, catch [0.2.0-nullsafety.1](https://pub.dev/packages/hexagon/versions/0.2.0-nullsafety.1)
I quickly migrated it for you. Please report back any issues.

**Comment by alexgrusu** [comment]
> Sure, catch [0.2.0-nullsafety.1](https://pub.dev/packages/hexagon/versions/0.2.0-nullsafety.1)
> I quickly migrated it for you. Please report back any issues.

Thank you, keep in touch with you.
